:toc-title: Table of contents
:toc:
:toclevels: 4

:tip-caption:  pass:[&#128681;]
:sectanchors:

:classdia-caption: Class diagram
:seqdia-caption: Sequence diagram

:source-highlighter: prettify

:imagesdir: ../../doc/images
:imagesoutdir: ../images
:testdir: ../../Tests
:sourcedir: ../../src
:plantumldir: ../plantuml
:rootdir: ../../
== Developer-Guide

=== Setup

This project uses JDK 21 and Maven 3.9.x (tested on version 3.9.15).

=== Start Cucumber scenario within the IDE (IntelliJ IDEA)

In "run configuration":

* set "main class" on `io.cucumber.junit.TigerCucumberRunner`

* set the following "glue code packages"

[source]
----
net.serenitybdd.cucumber.actors
de.gematik.test.tiger.hooks
de.gematik.test.tiger.glue
de.gematik.tim.test.glue
----

The Tiger-Framework was used for the development of this testsuite.
In the following link, you will find the link:https://gematik.github.io/app-Tiger/Tiger-User-Manual.html#_intellij[Tiger-Manual]
for more information.

To trigger the clean endpoints from IntelliJ, the run configuration must also include
`-Dcucumber.plugin=de.gematik.tim.test.glue.api.utils.cleaning.CucumberListener` as a VM option.

[[Disable-TLS]]
=== Disable TLS

To disable TLS, do not set the environment variables, and delete lines 2 and 3 in  link:{rootdir}tiger.yml[tiger.yml].

IMPORTANT: Line 1 "tigerProxy:" must remain.

[source,yml,linenums]
----
tigerProxy:
  tls:
    forwardMutualTlsIdentity: "${TIM_KEYSTORE};${TIM_KEYSTORE_PW};pkcs12"
----

With this configuration, all links in link:{sourcedir}/combine_items.json[combine_items.json] must be set to  `http`.

=== Cucumber-Test-Combinations-Maven-Plugin

The parameter plugin generates all possible combinations for each individual test case from the provided interfaces in link:{sourcedir}/combine_items.json[combine_items.json], based on the filters.
For this, all templates from the test folder are copied to the build folder and filled with the respective tables.
The processed files are used when the test suite is started.

With a small number of interfaces that lack sufficient variation in their properties, the plugin may quickly cause the build process to fail.
To ignore this, the following steps can be configured.

==== Disable prepare-items (autofill combine_items.json)

By default, the plugin queries the info interface and adds necessary tags and properties.
For more precise control, or if the info interface has not been fully implemented yet, the `combine_items.json` can be manually created and used.
For this, Maven can be run with the `disable-prepare-items` profile.

----
maven clean install -P disable-prepare-items
----

==== Disable break

With the `dont-break-preparation` profile, the plugin can be configured to no longer stop the build process in case of errors.
All possible information and combinations are generated.
An error log can later be viewed at `./target/generated-combine/errorLog.txt` .

=== Influence claim time

The parameter `-DclaimDuration=<seconds>` can be used to influence the duration for which a device should remain claimed.
Only integer second values are allowed.
Default value is 180 seconds.

=== Testcase id

Every testcase run is identified with the testcase name and an id that identifies the specific run.
This id is sent in every request in the header `Test-Case-Id`.
It is build like `<TestcaseId>/<TestrunUUID>`.

=== Setting up a custom pom.xml file

All shared configuration is defined in link:{rootdir}parent-pom.xml[parent-pom.xml].
To adapt the testsuite to your environment, you can create a custom POM that extends this parent and overrides the relevant properties.
This is especially useful if you want to maintain multiple configurations e.g. one for local development and one for CI.
Run it with `mvn clean verify -f my-custom-pom.xml`.

Minimal template:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <artifactId>my-custom</artifactId>
  <packaging>jar</packaging>

  <parent>
    <groupId>de.gematik.tim.test</groupId>
    <artifactId>parent</artifactId>
    <version>${revision}</version>
    <relativePath>parent-pom.xml</relativePath>
  </parent>

  <properties>
    <!-- Tiger configuration for your environment -->
    <tiger.config.file>
      ${project.basedir}/src/test/resources/tigerYml/tiger-my-custom.yml
    </tiger.config.file>
    <!-- combine-items file describing your test driver endpoints -->
    <combine.items.file>
      ${project.basedir}/src/test/resources/combineItems/combine_items_my_custom.json
    </combine.items.file>
    <!-- Feature template directories (comma-separated for multiple) -->
    <feature.template.dir>${feature.template.dir.V3}</feature.template.dir>
  </properties>
</project>
----

Three common properties you might want to customise:

. `tiger.config.file` – path to the Tiger YAML configuration for the target environment.
. `combine.items.file` – path to the combine-items JSON describing the test driver endpoints.
. `feature.template.dir` – one or more (comma-separated) directories containing the feature templates to use.

=== Known issues

. When generating the code from the link:https://github.com/gematik/api-ti-messenger/blob/main/src/openapi/TiMessengerTestTreiber.yaml[test driver interface], it may occur that additional `/` are created in the request path.
These can lead to incompatibilities.
This can be circumvented on the test suite side by removing the leading `/` in the INFO_PATH and DEVICES_PATH of the link:{sourcedir}/main/java/de/gematik/tim/test/glue/api/TestdriverApiPath.java[TestdriverApiPath] class.
